########################################
# Lantern Extractor Settings
########################################

########################################################
# GENERAL SETTINGS
#
#    EverQuestDirectory
#        Specifies the EverQuest installation path.
#        On Windows, you must use double backslashes
#        Example for Windows: C:\\EverQuest
#        Example for macOS: /Users/your.name/EQ/
#
#    LoggerVerbosity
#        Sets the minimum verbosity of the logger.
#        0 = info, 1 = warnings, 2 = errors
#
#    RawS3DExtract
#        Extracts the contents of the S3D archive as is.
#        true = export contents as they exist in their original formats.
#        false = extract contents, process WLD files, convert images to PNG.
#
#    ExportCharacterToSingleFolder
#        Exports all characters to the 'characters' folder.
#        Useful for batch importing into Unity.
#
#    ExportEquipmentToSingleFolder
#        Exports all equipment to the 'equipment' folder.
#        Useful for batch importing into Unity.
#
########################################################
EverQuestDirectory = "C:\\EQ"
UseMultithreading = true
LoggerVerbosity = 2
RawS3DExtract = false
ExportCharacterToSingleFolder = false
ExportEquipmentToSingleFolder = false

########################################################
# MODEL EXPORT SETTINGS
#
#    ModelExportFormat
#        Sets the desired export format for models.
#        0 = Intermediate (Unity importer)
#        1 = OBJ
#        2 = glTF
#
#    ExportZoneMeshGroups
#        Extracts the zone mesh with groups.
#        true = export each region mesh separately.
#        false = combine the zone into a single mesh (Unity importer supports only single mesh zone).
#
#    ExportHiddenGeometry
#        Includes hidden geometry (invisible boundaries) in the zone collision export.
#
#    ExportZoneWithObjects
#        Exports zone files in OBJ format with associated objects placed in the zone.
#
#    ExportGltfVertexColors
#        Exports vertex colors for glTF models.
#        Note: Default behavior of glTF renderers is to mix the vertex color with the base color,
#        which may not display correctly.
#
#    ExportGltfInGlbFormat
#        Exports glTF models in .GLB file format.
#        GLB packages the .glTF JSON, .bin, and textures into a single file.
#        This takes more space but makes models more portable.
#
#    ExportAllAnimationFrames
#        Exports an OBJ for each animation frame.
#        Note: This can use a lot of disk space if using OBJ format.
#        For glTF, skeletal models are exported with animations.
#
########################################################
ModelExportFormat = 0
ExportZoneMeshGroups = false
ExportHiddenGeometry = false
ExportZoneWithObjects = false
ExportGltfVertexColors = false
ExportGltfInGlbFormat = false
ExportAllAnimationFrames = false

########################################################
# SOUND AND MUSIC SETTINGS
#
#    ExportSoundsToSingleFolder
#        Exports all sounds to the 'sounds' folder.
#        Note: Some sounds with conflicting names may be overwritten.
#
#    CopyMusic
#        Copies client XMI music files to the 'Exports/Music' folder.
#        XMI files can be used in the Lantern client.
#
########################################################
ExportSoundsToSingleFolder = false
CopyMusic = true

########################################################
# CLIENT DATA SETTINGS
#
#    ClientDataToCopy
#        Specifies additional files to copy during extraction.
#        Files should be listed relative to `EverQuestDirectory`.
#
########################################################
ClientDataToCopy = ["spells.eff", "spdat.eff"]